
---
- hosts: all

# https://computingforgeeks.com/how-to-install-grafana-on-ubuntu-debian/

  tasks:

  - name: Ensure your Ubuntu / Debian system is up to date
    command: apt update
    become: yes

  - name: install usefull packages
    command: apt-get install -y gnupg2 curl software-properties-common
    become: yes

  - name: Add Grafana gpg key which allows you to install signed packages
    apt_key:
     url: https://packages.grafana.com/gpg.key
     state: present
    become: yes

  - name: install Grafana APT repository
    command: add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
    become: yes

  - name: update apt-get
    command: apt-get update
    become: yes

  - name: install Grafana
    command: apt-get -y install grafana
    become: yes

  - name: run grafana service
    command: systemctl enable --now grafana-server
    become: yes
