---
- hosts: all
  vars:
    groupId: prometheus
    userId: prometheus
    version: 2.20.0
    serviceName: prometheus

  tasks:

  - name: Creating prometheus user group
    group: name="{{groupId}}"
    become: true

  - name: Creating prometheus user
    user:
     name: "{{userId}}"
     group: "{{groupId}}"
     system: yes
     shell: "/sbin/nologin"
     comment: "{{userId}} nologin User"
     createhome: "no"
     state: present
    become: true

  - name: Install prometheus
    unarchive:
     src: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
     dest: /tmp/
     remote_src: yes

  - name: Copy prometheus file to bin
    copy:
     src: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
     dest: "/usr/local/bin/prometheus"
     owner: "{{userId}}"
     group: "{{groupId}}"
     remote_src: yes
     mode: 0755
    become: true

  - name: Delete prometheus tmp folder
    file:
     path: '/tmp/prometheus-{{ version }}.linux-amd64'
     state: absent

  - name: Create /etc/prometheus directory
    file:
     path: "/etc/prometheus"
     state: directory
    become: true

  - name: Create /var/lib/prometheus directory
    file:
     path: "/var/lib/prometheus"
     state: directory
    become: true

  - name: config file
    become: true
    copy:
     src: prometheus.yml
     dest: /etc/prometheus/prometheus.yml

  - name: Copy systemd init file
    become: yes
    become_user: root
    copy:
     src: init.service
     dest: /lib/systemd/system/prometheus.service

  - name: Start prometheus service
    become: yes
    systemd:
     state: restarted
     daemon_reload: yes
     enabled: yes
     name: prometheus

  - name: Check if prometheus is accessible
    uri:
     url: http://localhost:9090
     method: GET
     status_code: 200
