global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.1.5:9100','10.0.1.6:9100','10.0.1.7:9100','10.0.1.8:9100','10.0.1.9:9100']
