---
- hosts: all
  vars:
    groupId: prometheus
    userId: prometheus
    version: 2.20.0
    serviceName: prometheus
    user: myadmin
    server_file: "/home/{{user}}/onboardserver/server.txt"

  tasks:

  - name: Creating prometheus user group
    group: name="{{groupId}}"
    become: true

  - name: Creating prometheus user
    user:
     name: "{{userId}}"
     group: "{{groupId}}"
     system: yes
     shell: "/sbin/nologin"
     comment: "{{userId}} nologin User"
     createhome: "no"
     state: present
    become: true

  - name: Install prometheus
    unarchive:
     src: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
     dest: /tmp/
     remote_src: yes

  - name: Copy prometheus file to bin
    copy:
     src: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
     dest: "/usr/local/bin/prometheus"
     owner: "{{userId}}"
     group: "{{groupId}}"
     remote_src: yes
     mode: 0755
    become: yes

  - name: Delete prometheus tmp folder
    file:
     path: '/tmp/prometheus-{{ version }}.linux-amd64'
     state: absent

  - name: Create /etc/prometheus directory
    file:
     path: "/etc/prometheus"
     state: directory
    become: yes

  - name: Create /var/lib/prometheus directory
    file:
     path: "/var/lib/prometheus"
     state: directory
    become: yes

  - name: Create prometheus workspace directory
    file:
     path: "/home/{{user}}/prometheus"
     state: directory

  - name: Copy config file
    copy:
     src: prometheus.yml
     dest: /home/{{user}}/prometheus/prometheus.yml

  - name: Copy script file
    copy:
     src: update_monitored_servers.sh
     dest: /home/{{user}}/prometheus/update_monitored_servers.sh

  - name: Make executable script
    file:
     dest: "/home/{{user}}/prometheus/update_monitored_servers.sh"
     mode: a+x

  - name: Execute script
    command: ./update_monitored_servers.sh {{server_file}}
    args:
     chdir: "/home/{{user}}/prometheus"

  - name: Copy config file
    copy:
     src: /home/{{user}}/prometheus/prometheus-new.yml
     dest: /etc/prometheus/prometheus.yml
     remote_src: yes
    become: yes

  - name: Copy systemd init file
    copy:
     src: init.service
     dest: /lib/systemd/system/prometheus.service
    become: yes

  - name: Start prometheus service
    systemd:
     state: restarted
     daemon_reload: yes
     enabled: yes
     name: prometheus
    become: yes

  - name: Check if prometheus is accessible
    uri:
     url: http://localhost:9090
     method: GET
     status_code: 200
