---
- hosts: all
  vars:
    groupId: node_exporter
    userId: node_exporter
    version: 0.16.0
    serviceName: node_exporter

  tasks:

  - name: Creating prometheus user group
    group: name="{{groupId}}"
    become: true

  - name: Creating prometheus user
    user:
     name: "{{userId}}"
     group: "{{groupId}}"
     system: yes
     shell: "/sbin/nologin"
     comment: "{{userId}} nologin User"
     createhome: "no"
     state: present
    become: true

  - name: Install prometheus node exporter
    unarchive:
     src: "https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz"
     dest: /tmp/
     remote_src: yes

  - name: Copy prometheus node exporter file to bin
    copy:
     src: "/tmp/node_exporter-{{ version }}.linux-amd64/node_exporter"
     dest: "/usr/local/bin/node_exporter"
     owner: "{{userId}}"
     group: "{{groupId}}"
     remote_src: yes
     mode: 0755
    become: true

  - name: Delete node exporter tmp folder
    file:
     path: '/tmp/node_exporter-{{ version }}.linux-amd64'
     state: absent

  - name: Copy systemd init file
    become: yes
    copy:
     src: init.service
     dest: /lib/systemd/system/node_exporter.service

  - name: Start node_exporter service
    become: yes
    systemd:
     state: restarted
     daemon_reload: yes
     enabled: yes
     name: node_exporter

  - name: Check if node_exporter provides metrics
    uri:
     url: http://localhost:9100/metrics
     method: GET
     status_code: 200
