---
- hosts: all
  remote_user: "{{user}}"

  # The target of this scripts is the jumphost server
  # ansible-playbook --vault-id /Users/andreabortolossi/ansible_vault_password -i ../myazure_rm.yml onboardservers.yml -l tag_environment_management

  vars:
    script_name: setup_bind9.sh
    script_path_origin: ../scripts/{{script_name}}
    script_path_target: /home/{{user}}/scripts/
    service_name: bind9
    log_directory: /var/log/named
    user: ubuntu

  tasks:

    - name: Install bind
      become: yes
      apt:
       pkg:
       - bind9
       - bind9-doc

    - name: Create script directory on target server
      file:
       path: "{{script_path_target}}"
       state: directory

    - name: Copy script file to target
      copy:
       src: "{{script_path_origin}}"
       dest: "{{script_path_target}}"

    - name: Make executable "{{script_name}}"
      file:
        dest: "{{script_path_target}}/{{script_name}}"
        mode: a+x

    - name: Execute "{{script_name}}"
      become: yes
      command: ./{{script_name}}
      args:
        chdir: "{{script_path_target}}"

    - name: restart service {{service_name}}, in all cases, also issue daemon-reload to pick up config changes
      become: yes
      systemd:
       state: restarted
       daemon_reload: yes
       enabled: yes
       name: "{{service_name}}"
